// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1NKwYowzGJlbNkDbxmOFR63dV9L8vspo',
    appId: '1:1053771278981:web:f2aac0ea9bbbd3c61117ec',
    messagingSenderId: '1053771278981',
    projectId: 'base-e6eec',
    authDomain: 'base-e6eec.firebaseapp.com',
    storageBucket: 'base-e6eec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0n_m8_7uR27xPfAfVMjxZEZSjYmnfNFs',
    appId: '1:1053771278981:android:4b126a3a9221d2281117ec',
    messagingSenderId: '1053771278981',
    projectId: 'base-e6eec',
    storageBucket: 'base-e6eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMerz_AWMV-BFaH1gQubnpv20VL6UQAXA',
    appId: '1:1053771278981:ios:c7ca4383671d64611117ec',
    messagingSenderId: '1053771278981',
    projectId: 'base-e6eec',
    storageBucket: 'base-e6eec.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMerz_AWMV-BFaH1gQubnpv20VL6UQAXA',
    appId: '1:1053771278981:ios:c7ca4383671d64611117ec',
    messagingSenderId: '1053771278981',
    projectId: 'base-e6eec',
    storageBucket: 'base-e6eec.firebasestorage.app',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1NKwYowzGJlbNkDbxmOFR63dV9L8vspo',
    appId: '1:1053771278981:web:2f24a7a7dea834181117ec',
    messagingSenderId: '1053771278981',
    projectId: 'base-e6eec',
    authDomain: 'base-e6eec.firebaseapp.com',
    storageBucket: 'base-e6eec.firebasestorage.app',
  );
}
